/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as SsoCallbackImport } from './routes/sso.callback'
import { Route as AppCampaignIdRouteImport } from './routes/app/$campaignId/route'
import { Route as AppCampaignIdIndexImport } from './routes/app/$campaignId/index'
import { Route as AppCampaignIdSessionsImport } from './routes/app/$campaignId/sessions'
import { Route as AppCampaignIdSessionsSessionIdImport } from './routes/app/$campaignId/sessions.$sessionId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const SsoCallbackRoute = SsoCallbackImport.update({
  id: '/sso/callback',
  path: '/sso/callback',
  getParentRoute: () => rootRoute,
} as any)

const AppCampaignIdRouteRoute = AppCampaignIdRouteImport.update({
  id: '/app/$campaignId',
  path: '/app/$campaignId',
  getParentRoute: () => rootRoute,
} as any)

const AppCampaignIdIndexRoute = AppCampaignIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignIdRouteRoute,
} as any)

const AppCampaignIdSessionsRoute = AppCampaignIdSessionsImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppCampaignIdRouteRoute,
} as any)

const AppCampaignIdSessionsSessionIdRoute =
  AppCampaignIdSessionsSessionIdImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AppCampaignIdSessionsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/$campaignId': {
      id: '/app/$campaignId'
      path: '/app/$campaignId'
      fullPath: '/app/$campaignId'
      preLoaderRoute: typeof AppCampaignIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/sso/callback': {
      id: '/sso/callback'
      path: '/sso/callback'
      fullPath: '/sso/callback'
      preLoaderRoute: typeof SsoCallbackImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/$campaignId/sessions': {
      id: '/app/$campaignId/sessions'
      path: '/sessions'
      fullPath: '/app/$campaignId/sessions'
      preLoaderRoute: typeof AppCampaignIdSessionsImport
      parentRoute: typeof AppCampaignIdRouteImport
    }
    '/app/$campaignId/': {
      id: '/app/$campaignId/'
      path: '/'
      fullPath: '/app/$campaignId/'
      preLoaderRoute: typeof AppCampaignIdIndexImport
      parentRoute: typeof AppCampaignIdRouteImport
    }
    '/app/$campaignId/sessions/$sessionId': {
      id: '/app/$campaignId/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/app/$campaignId/sessions/$sessionId'
      preLoaderRoute: typeof AppCampaignIdSessionsSessionIdImport
      parentRoute: typeof AppCampaignIdSessionsImport
    }
  }
}

// Create and export the route tree

interface AppCampaignIdSessionsRouteChildren {
  AppCampaignIdSessionsSessionIdRoute: typeof AppCampaignIdSessionsSessionIdRoute
}

const AppCampaignIdSessionsRouteChildren: AppCampaignIdSessionsRouteChildren = {
  AppCampaignIdSessionsSessionIdRoute: AppCampaignIdSessionsSessionIdRoute,
}

const AppCampaignIdSessionsRouteWithChildren =
  AppCampaignIdSessionsRoute._addFileChildren(
    AppCampaignIdSessionsRouteChildren,
  )

interface AppCampaignIdRouteRouteChildren {
  AppCampaignIdSessionsRoute: typeof AppCampaignIdSessionsRouteWithChildren
  AppCampaignIdIndexRoute: typeof AppCampaignIdIndexRoute
}

const AppCampaignIdRouteRouteChildren: AppCampaignIdRouteRouteChildren = {
  AppCampaignIdSessionsRoute: AppCampaignIdSessionsRouteWithChildren,
  AppCampaignIdIndexRoute: AppCampaignIdIndexRoute,
}

const AppCampaignIdRouteRouteWithChildren =
  AppCampaignIdRouteRoute._addFileChildren(AppCampaignIdRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$campaignId': typeof AppCampaignIdRouteRouteWithChildren
  '/sso/callback': typeof SsoCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/$campaignId/sessions': typeof AppCampaignIdSessionsRouteWithChildren
  '/app/$campaignId/': typeof AppCampaignIdIndexRoute
  '/app/$campaignId/sessions/$sessionId': typeof AppCampaignIdSessionsSessionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sso/callback': typeof SsoCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/$campaignId/sessions': typeof AppCampaignIdSessionsRouteWithChildren
  '/app/$campaignId': typeof AppCampaignIdIndexRoute
  '/app/$campaignId/sessions/$sessionId': typeof AppCampaignIdSessionsSessionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app/$campaignId': typeof AppCampaignIdRouteRouteWithChildren
  '/sso/callback': typeof SsoCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/$campaignId/sessions': typeof AppCampaignIdSessionsRouteWithChildren
  '/app/$campaignId/': typeof AppCampaignIdIndexRoute
  '/app/$campaignId/sessions/$sessionId': typeof AppCampaignIdSessionsSessionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$campaignId'
    | '/sso/callback'
    | '/app'
    | '/app/$campaignId/sessions'
    | '/app/$campaignId/'
    | '/app/$campaignId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sso/callback'
    | '/app'
    | '/app/$campaignId/sessions'
    | '/app/$campaignId'
    | '/app/$campaignId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/app/$campaignId'
    | '/sso/callback'
    | '/app/'
    | '/app/$campaignId/sessions'
    | '/app/$campaignId/'
    | '/app/$campaignId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppCampaignIdRouteRoute: typeof AppCampaignIdRouteRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
  AppIndexRoute: typeof AppIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppCampaignIdRouteRoute: AppCampaignIdRouteRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
  AppIndexRoute: AppIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/$campaignId",
        "/sso/callback",
        "/app/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app/$campaignId": {
      "filePath": "app/$campaignId/route.tsx",
      "children": [
        "/app/$campaignId/sessions",
        "/app/$campaignId/"
      ]
    },
    "/sso/callback": {
      "filePath": "sso.callback.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    },
    "/app/$campaignId/sessions": {
      "filePath": "app/$campaignId/sessions.tsx",
      "parent": "/app/$campaignId",
      "children": [
        "/app/$campaignId/sessions/$sessionId"
      ]
    },
    "/app/$campaignId/": {
      "filePath": "app/$campaignId/index.tsx",
      "parent": "/app/$campaignId"
    },
    "/app/$campaignId/sessions/$sessionId": {
      "filePath": "app/$campaignId/sessions.$sessionId.tsx",
      "parent": "/app/$campaignId/sessions"
    }
  }
}
ROUTE_MANIFEST_END */
